// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magento2go/client/amazon_payment_address_management_v1"
	"magento2go/client/amazon_payment_order_information_management_v1"
	"magento2go/client/catalog_attribute_set_repository_v1"
	"magento2go/client/catalog_category_link_management_v1"
	"magento2go/client/catalog_category_management_v1"
	"magento2go/client/catalog_category_repository_v1"
	"magento2go/client/catalog_inventory_stock_registry_v1"
	"magento2go/client/catalog_product_attribute_group_repository_v1"
	"magento2go/client/catalog_product_attribute_management_v1"
	"magento2go/client/catalog_product_attribute_media_gallery_management_v1"
	"magento2go/client/catalog_product_attribute_option_management_v1"
	"magento2go/client/catalog_product_attribute_repository_v1"
	"magento2go/client/catalog_product_custom_option_repository_v1"
	"magento2go/client/catalog_product_link_management_v1"
	"magento2go/client/catalog_product_link_type_list_v1"
	"magento2go/client/catalog_product_media_attribute_management_v1"
	"magento2go/client/catalog_product_render_list_v1"
	"magento2go/client/catalog_product_repository_v1"
	"magento2go/client/catalog_product_tier_price_management_v1"
	"magento2go/client/catalog_product_type_list_v1"
	"magento2go/client/checkout_guest_payment_information_management_v1"
	"magento2go/client/checkout_guest_shipping_information_management_v1"
	"magento2go/client/checkout_guest_totals_information_management_v1"
	"magento2go/client/cms_block_repository_v1"
	"magento2go/client/cms_page_repository_v1"
	"magento2go/client/configurable_product_link_management_v1"
	"magento2go/client/configurable_product_option_repository_v1"
	"magento2go/client/customer_account_management_v1"
	"magento2go/client/directory_country_information_acquirer_v1"
	"magento2go/client/directory_currency_information_acquirer_v1"
	"magento2go/client/gift_message_guest_cart_repository_v1"
	"magento2go/client/gift_message_guest_item_repository_v1"
	"magento2go/client/integration_admin_token_service_v1"
	"magento2go/client/integration_customer_token_service_v1"
	"magento2go/client/inventory_in_store_pickup_api_get_pickup_locations_v1"
	"magento2go/client/pay_pal_braintree_auth_v1"
	"magento2go/client/quote_guest_billing_address_management_v1"
	"magento2go/client/quote_guest_cart_item_repository_v1"
	"magento2go/client/quote_guest_cart_management_v1"
	"magento2go/client/quote_guest_cart_repository_v1"
	"magento2go/client/quote_guest_cart_total_management_v1"
	"magento2go/client/quote_guest_cart_total_repository_v1"
	"magento2go/client/quote_guest_coupon_management_v1"
	"magento2go/client/quote_guest_payment_method_management_v1"
	"magento2go/client/quote_guest_shipment_estimation_v1"
	"magento2go/client/quote_guest_shipping_method_management_v1"
	"magento2go/client/search_v1"
	"magento2go/client/store_group_repository_v1"
	"magento2go/client/store_store_config_manager_v1"
	"magento2go/client/store_store_repository_v1"
	"magento2go/client/store_website_repository_v1"
	"magento2go/client/vertex_address_validation_address_management_v1"
	"magento2go/client/vertex_address_validation_api_guest_cleanse_address_v1"
)

// Default magento community HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "magento.test"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/rest/default"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new magento community HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MagentoCommunity {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new magento community HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *MagentoCommunity {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new magento community client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MagentoCommunity {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(MagentoCommunity)
	cli.Transport = transport
	cli.AmazonPaymentAddressManagementV1 = amazon_payment_address_management_v1.New(transport, formats)
	cli.AmazonPaymentOrderInformationManagementV1 = amazon_payment_order_information_management_v1.New(transport, formats)
	cli.CatalogAttributeSetRepositoryV1 = catalog_attribute_set_repository_v1.New(transport, formats)
	cli.CatalogCategoryLinkManagementV1 = catalog_category_link_management_v1.New(transport, formats)
	cli.CatalogCategoryManagementV1 = catalog_category_management_v1.New(transport, formats)
	cli.CatalogCategoryRepositoryV1 = catalog_category_repository_v1.New(transport, formats)
	cli.CatalogInventoryStockRegistryV1 = catalog_inventory_stock_registry_v1.New(transport, formats)
	cli.CatalogProductAttributeGroupRepositoryV1 = catalog_product_attribute_group_repository_v1.New(transport, formats)
	cli.CatalogProductAttributeManagementV1 = catalog_product_attribute_management_v1.New(transport, formats)
	cli.CatalogProductAttributeMediaGalleryManagementV1 = catalog_product_attribute_media_gallery_management_v1.New(transport, formats)
	cli.CatalogProductAttributeOptionManagementV1 = catalog_product_attribute_option_management_v1.New(transport, formats)
	cli.CatalogProductAttributeRepositoryV1 = catalog_product_attribute_repository_v1.New(transport, formats)
	cli.CatalogProductCustomOptionRepositoryV1 = catalog_product_custom_option_repository_v1.New(transport, formats)
	cli.CatalogProductLinkManagementV1 = catalog_product_link_management_v1.New(transport, formats)
	cli.CatalogProductLinkTypeListV1 = catalog_product_link_type_list_v1.New(transport, formats)
	cli.CatalogProductMediaAttributeManagementV1 = catalog_product_media_attribute_management_v1.New(transport, formats)
	cli.CatalogProductRenderListV1 = catalog_product_render_list_v1.New(transport, formats)
	cli.CatalogProductRepositoryV1 = catalog_product_repository_v1.New(transport, formats)
	cli.CatalogProductTierPriceManagementV1 = catalog_product_tier_price_management_v1.New(transport, formats)
	cli.CatalogProductTypeListV1 = catalog_product_type_list_v1.New(transport, formats)
	cli.CheckoutGuestPaymentInformationManagementV1 = checkout_guest_payment_information_management_v1.New(transport, formats)
	cli.CheckoutGuestShippingInformationManagementV1 = checkout_guest_shipping_information_management_v1.New(transport, formats)
	cli.CheckoutGuestTotalsInformationManagementV1 = checkout_guest_totals_information_management_v1.New(transport, formats)
	cli.CmsBlockRepositoryV1 = cms_block_repository_v1.New(transport, formats)
	cli.CmsPageRepositoryV1 = cms_page_repository_v1.New(transport, formats)
	cli.ConfigurableProductLinkManagementV1 = configurable_product_link_management_v1.New(transport, formats)
	cli.ConfigurableProductOptionRepositoryV1 = configurable_product_option_repository_v1.New(transport, formats)
	cli.CustomerAccountManagementV1 = customer_account_management_v1.New(transport, formats)
	cli.DirectoryCountryInformationAcquirerV1 = directory_country_information_acquirer_v1.New(transport, formats)
	cli.DirectoryCurrencyInformationAcquirerV1 = directory_currency_information_acquirer_v1.New(transport, formats)
	cli.GiftMessageGuestCartRepositoryV1 = gift_message_guest_cart_repository_v1.New(transport, formats)
	cli.GiftMessageGuestItemRepositoryV1 = gift_message_guest_item_repository_v1.New(transport, formats)
	cli.IntegrationAdminTokenServiceV1 = integration_admin_token_service_v1.New(transport, formats)
	cli.IntegrationCustomerTokenServiceV1 = integration_customer_token_service_v1.New(transport, formats)
	cli.InventoryInStorePickupAPIGetPickupLocationsV1 = inventory_in_store_pickup_api_get_pickup_locations_v1.New(transport, formats)
	cli.PayPalBraintreeAuthV1 = pay_pal_braintree_auth_v1.New(transport, formats)
	cli.QuoteGuestBillingAddressManagementV1 = quote_guest_billing_address_management_v1.New(transport, formats)
	cli.QuoteGuestCartItemRepositoryV1 = quote_guest_cart_item_repository_v1.New(transport, formats)
	cli.QuoteGuestCartManagementV1 = quote_guest_cart_management_v1.New(transport, formats)
	cli.QuoteGuestCartRepositoryV1 = quote_guest_cart_repository_v1.New(transport, formats)
	cli.QuoteGuestCartTotalManagementV1 = quote_guest_cart_total_management_v1.New(transport, formats)
	cli.QuoteGuestCartTotalRepositoryV1 = quote_guest_cart_total_repository_v1.New(transport, formats)
	cli.QuoteGuestCouponManagementV1 = quote_guest_coupon_management_v1.New(transport, formats)
	cli.QuoteGuestPaymentMethodManagementV1 = quote_guest_payment_method_management_v1.New(transport, formats)
	cli.QuoteGuestShipmentEstimationV1 = quote_guest_shipment_estimation_v1.New(transport, formats)
	cli.QuoteGuestShippingMethodManagementV1 = quote_guest_shipping_method_management_v1.New(transport, formats)
	cli.SearchV1 = search_v1.New(transport, formats)
	cli.StoreGroupRepositoryV1 = store_group_repository_v1.New(transport, formats)
	cli.StoreStoreConfigManagerV1 = store_store_config_manager_v1.New(transport, formats)
	cli.StoreStoreRepositoryV1 = store_store_repository_v1.New(transport, formats)
	cli.StoreWebsiteRepositoryV1 = store_website_repository_v1.New(transport, formats)
	cli.VertexAddressValidationAddressManagementV1 = vertex_address_validation_address_management_v1.New(transport, formats)
	cli.VertexAddressValidationAPIGuestCleanseAddressV1 = vertex_address_validation_api_guest_cleanse_address_v1.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// MagentoCommunity is a client for magento community
type MagentoCommunity struct {
	AmazonPaymentAddressManagementV1 amazon_payment_address_management_v1.ClientService

	AmazonPaymentOrderInformationManagementV1 amazon_payment_order_information_management_v1.ClientService

	CatalogAttributeSetRepositoryV1 catalog_attribute_set_repository_v1.ClientService

	CatalogCategoryLinkManagementV1 catalog_category_link_management_v1.ClientService

	CatalogCategoryManagementV1 catalog_category_management_v1.ClientService

	CatalogCategoryRepositoryV1 catalog_category_repository_v1.ClientService

	CatalogInventoryStockRegistryV1 catalog_inventory_stock_registry_v1.ClientService

	CatalogProductAttributeGroupRepositoryV1 catalog_product_attribute_group_repository_v1.ClientService

	CatalogProductAttributeManagementV1 catalog_product_attribute_management_v1.ClientService

	CatalogProductAttributeMediaGalleryManagementV1 catalog_product_attribute_media_gallery_management_v1.ClientService

	CatalogProductAttributeOptionManagementV1 catalog_product_attribute_option_management_v1.ClientService

	CatalogProductAttributeRepositoryV1 catalog_product_attribute_repository_v1.ClientService

	CatalogProductCustomOptionRepositoryV1 catalog_product_custom_option_repository_v1.ClientService

	CatalogProductLinkManagementV1 catalog_product_link_management_v1.ClientService

	CatalogProductLinkTypeListV1 catalog_product_link_type_list_v1.ClientService

	CatalogProductMediaAttributeManagementV1 catalog_product_media_attribute_management_v1.ClientService

	CatalogProductRenderListV1 catalog_product_render_list_v1.ClientService

	CatalogProductRepositoryV1 catalog_product_repository_v1.ClientService

	CatalogProductTierPriceManagementV1 catalog_product_tier_price_management_v1.ClientService

	CatalogProductTypeListV1 catalog_product_type_list_v1.ClientService

	CheckoutGuestPaymentInformationManagementV1 checkout_guest_payment_information_management_v1.ClientService

	CheckoutGuestShippingInformationManagementV1 checkout_guest_shipping_information_management_v1.ClientService

	CheckoutGuestTotalsInformationManagementV1 checkout_guest_totals_information_management_v1.ClientService

	CmsBlockRepositoryV1 cms_block_repository_v1.ClientService

	CmsPageRepositoryV1 cms_page_repository_v1.ClientService

	ConfigurableProductLinkManagementV1 configurable_product_link_management_v1.ClientService

	ConfigurableProductOptionRepositoryV1 configurable_product_option_repository_v1.ClientService

	CustomerAccountManagementV1 customer_account_management_v1.ClientService

	DirectoryCountryInformationAcquirerV1 directory_country_information_acquirer_v1.ClientService

	DirectoryCurrencyInformationAcquirerV1 directory_currency_information_acquirer_v1.ClientService

	GiftMessageGuestCartRepositoryV1 gift_message_guest_cart_repository_v1.ClientService

	GiftMessageGuestItemRepositoryV1 gift_message_guest_item_repository_v1.ClientService

	IntegrationAdminTokenServiceV1 integration_admin_token_service_v1.ClientService

	IntegrationCustomerTokenServiceV1 integration_customer_token_service_v1.ClientService

	InventoryInStorePickupAPIGetPickupLocationsV1 inventory_in_store_pickup_api_get_pickup_locations_v1.ClientService

	PayPalBraintreeAuthV1 pay_pal_braintree_auth_v1.ClientService

	QuoteGuestBillingAddressManagementV1 quote_guest_billing_address_management_v1.ClientService

	QuoteGuestCartItemRepositoryV1 quote_guest_cart_item_repository_v1.ClientService

	QuoteGuestCartManagementV1 quote_guest_cart_management_v1.ClientService

	QuoteGuestCartRepositoryV1 quote_guest_cart_repository_v1.ClientService

	QuoteGuestCartTotalManagementV1 quote_guest_cart_total_management_v1.ClientService

	QuoteGuestCartTotalRepositoryV1 quote_guest_cart_total_repository_v1.ClientService

	QuoteGuestCouponManagementV1 quote_guest_coupon_management_v1.ClientService

	QuoteGuestPaymentMethodManagementV1 quote_guest_payment_method_management_v1.ClientService

	QuoteGuestShipmentEstimationV1 quote_guest_shipment_estimation_v1.ClientService

	QuoteGuestShippingMethodManagementV1 quote_guest_shipping_method_management_v1.ClientService

	SearchV1 search_v1.ClientService

	StoreGroupRepositoryV1 store_group_repository_v1.ClientService

	StoreStoreConfigManagerV1 store_store_config_manager_v1.ClientService

	StoreStoreRepositoryV1 store_store_repository_v1.ClientService

	StoreWebsiteRepositoryV1 store_website_repository_v1.ClientService

	VertexAddressValidationAddressManagementV1 vertex_address_validation_address_management_v1.ClientService

	VertexAddressValidationAPIGuestCleanseAddressV1 vertex_address_validation_api_guest_cleanse_address_v1.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MagentoCommunity) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.AmazonPaymentAddressManagementV1.SetTransport(transport)
	c.AmazonPaymentOrderInformationManagementV1.SetTransport(transport)
	c.CatalogAttributeSetRepositoryV1.SetTransport(transport)
	c.CatalogCategoryLinkManagementV1.SetTransport(transport)
	c.CatalogCategoryManagementV1.SetTransport(transport)
	c.CatalogCategoryRepositoryV1.SetTransport(transport)
	c.CatalogInventoryStockRegistryV1.SetTransport(transport)
	c.CatalogProductAttributeGroupRepositoryV1.SetTransport(transport)
	c.CatalogProductAttributeManagementV1.SetTransport(transport)
	c.CatalogProductAttributeMediaGalleryManagementV1.SetTransport(transport)
	c.CatalogProductAttributeOptionManagementV1.SetTransport(transport)
	c.CatalogProductAttributeRepositoryV1.SetTransport(transport)
	c.CatalogProductCustomOptionRepositoryV1.SetTransport(transport)
	c.CatalogProductLinkManagementV1.SetTransport(transport)
	c.CatalogProductLinkTypeListV1.SetTransport(transport)
	c.CatalogProductMediaAttributeManagementV1.SetTransport(transport)
	c.CatalogProductRenderListV1.SetTransport(transport)
	c.CatalogProductRepositoryV1.SetTransport(transport)
	c.CatalogProductTierPriceManagementV1.SetTransport(transport)
	c.CatalogProductTypeListV1.SetTransport(transport)
	c.CheckoutGuestPaymentInformationManagementV1.SetTransport(transport)
	c.CheckoutGuestShippingInformationManagementV1.SetTransport(transport)
	c.CheckoutGuestTotalsInformationManagementV1.SetTransport(transport)
	c.CmsBlockRepositoryV1.SetTransport(transport)
	c.CmsPageRepositoryV1.SetTransport(transport)
	c.ConfigurableProductLinkManagementV1.SetTransport(transport)
	c.ConfigurableProductOptionRepositoryV1.SetTransport(transport)
	c.CustomerAccountManagementV1.SetTransport(transport)
	c.DirectoryCountryInformationAcquirerV1.SetTransport(transport)
	c.DirectoryCurrencyInformationAcquirerV1.SetTransport(transport)
	c.GiftMessageGuestCartRepositoryV1.SetTransport(transport)
	c.GiftMessageGuestItemRepositoryV1.SetTransport(transport)
	c.IntegrationAdminTokenServiceV1.SetTransport(transport)
	c.IntegrationCustomerTokenServiceV1.SetTransport(transport)
	c.InventoryInStorePickupAPIGetPickupLocationsV1.SetTransport(transport)
	c.PayPalBraintreeAuthV1.SetTransport(transport)
	c.QuoteGuestBillingAddressManagementV1.SetTransport(transport)
	c.QuoteGuestCartItemRepositoryV1.SetTransport(transport)
	c.QuoteGuestCartManagementV1.SetTransport(transport)
	c.QuoteGuestCartRepositoryV1.SetTransport(transport)
	c.QuoteGuestCartTotalManagementV1.SetTransport(transport)
	c.QuoteGuestCartTotalRepositoryV1.SetTransport(transport)
	c.QuoteGuestCouponManagementV1.SetTransport(transport)
	c.QuoteGuestPaymentMethodManagementV1.SetTransport(transport)
	c.QuoteGuestShipmentEstimationV1.SetTransport(transport)
	c.QuoteGuestShippingMethodManagementV1.SetTransport(transport)
	c.SearchV1.SetTransport(transport)
	c.StoreGroupRepositoryV1.SetTransport(transport)
	c.StoreStoreConfigManagerV1.SetTransport(transport)
	c.StoreStoreRepositoryV1.SetTransport(transport)
	c.StoreWebsiteRepositoryV1.SetTransport(transport)
	c.VertexAddressValidationAddressManagementV1.SetTransport(transport)
	c.VertexAddressValidationAPIGuestCleanseAddressV1.SetTransport(transport)
}
