// Code generated by go-swagger; DO NOT EDIT.

package store_store_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// StoreStoreRepositoryV1GetListGetReader is a Reader for the StoreStoreRepositoryV1GetListGet structure.
type StoreStoreRepositoryV1GetListGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StoreStoreRepositoryV1GetListGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStoreStoreRepositoryV1GetListGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStoreStoreRepositoryV1GetListGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStoreStoreRepositoryV1GetListGetOK creates a StoreStoreRepositoryV1GetListGetOK with default headers values
func NewStoreStoreRepositoryV1GetListGetOK() *StoreStoreRepositoryV1GetListGetOK {
	return &StoreStoreRepositoryV1GetListGetOK{}
}

/* StoreStoreRepositoryV1GetListGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type StoreStoreRepositoryV1GetListGetOK struct {
	Payload []*models.StoreDataStoreInterface
}

func (o *StoreStoreRepositoryV1GetListGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/store/storeViews][%d] storeStoreRepositoryV1GetListGetOK  %+v", 200, o.Payload)
}
func (o *StoreStoreRepositoryV1GetListGetOK) GetPayload() []*models.StoreDataStoreInterface {
	return o.Payload
}

func (o *StoreStoreRepositoryV1GetListGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStoreStoreRepositoryV1GetListGetDefault creates a StoreStoreRepositoryV1GetListGetDefault with default headers values
func NewStoreStoreRepositoryV1GetListGetDefault(code int) *StoreStoreRepositoryV1GetListGetDefault {
	return &StoreStoreRepositoryV1GetListGetDefault{
		_statusCode: code,
	}
}

/* StoreStoreRepositoryV1GetListGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type StoreStoreRepositoryV1GetListGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the store store repository v1 get list get default response
func (o *StoreStoreRepositoryV1GetListGetDefault) Code() int {
	return o._statusCode
}

func (o *StoreStoreRepositoryV1GetListGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/store/storeViews][%d] storeStoreRepositoryV1GetListGet default  %+v", o._statusCode, o.Payload)
}
func (o *StoreStoreRepositoryV1GetListGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *StoreStoreRepositoryV1GetListGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
