// Code generated by go-swagger; DO NOT EDIT.

package catalog_product_custom_option_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// CatalogProductCustomOptionRepositoryV1GetListGetReader is a Reader for the CatalogProductCustomOptionRepositoryV1GetListGet structure.
type CatalogProductCustomOptionRepositoryV1GetListGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CatalogProductCustomOptionRepositoryV1GetListGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCatalogProductCustomOptionRepositoryV1GetListGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCatalogProductCustomOptionRepositoryV1GetListGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCatalogProductCustomOptionRepositoryV1GetListGetOK creates a CatalogProductCustomOptionRepositoryV1GetListGetOK with default headers values
func NewCatalogProductCustomOptionRepositoryV1GetListGetOK() *CatalogProductCustomOptionRepositoryV1GetListGetOK {
	return &CatalogProductCustomOptionRepositoryV1GetListGetOK{}
}

/* CatalogProductCustomOptionRepositoryV1GetListGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type CatalogProductCustomOptionRepositoryV1GetListGetOK struct {
	Payload []*models.CatalogDataProductCustomOptionInterface
}

func (o *CatalogProductCustomOptionRepositoryV1GetListGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/products/{sku}/options][%d] catalogProductCustomOptionRepositoryV1GetListGetOK  %+v", 200, o.Payload)
}
func (o *CatalogProductCustomOptionRepositoryV1GetListGetOK) GetPayload() []*models.CatalogDataProductCustomOptionInterface {
	return o.Payload
}

func (o *CatalogProductCustomOptionRepositoryV1GetListGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogProductCustomOptionRepositoryV1GetListGetDefault creates a CatalogProductCustomOptionRepositoryV1GetListGetDefault with default headers values
func NewCatalogProductCustomOptionRepositoryV1GetListGetDefault(code int) *CatalogProductCustomOptionRepositoryV1GetListGetDefault {
	return &CatalogProductCustomOptionRepositoryV1GetListGetDefault{
		_statusCode: code,
	}
}

/* CatalogProductCustomOptionRepositoryV1GetListGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type CatalogProductCustomOptionRepositoryV1GetListGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the catalog product custom option repository v1 get list get default response
func (o *CatalogProductCustomOptionRepositoryV1GetListGetDefault) Code() int {
	return o._statusCode
}

func (o *CatalogProductCustomOptionRepositoryV1GetListGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/products/{sku}/options][%d] catalogProductCustomOptionRepositoryV1GetListGet default  %+v", o._statusCode, o.Payload)
}
func (o *CatalogProductCustomOptionRepositoryV1GetListGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CatalogProductCustomOptionRepositoryV1GetListGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
