// Code generated by go-swagger; DO NOT EDIT.

package catalog_product_link_type_list_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new catalog product link type list v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog product link type list v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CatalogProductLinkTypeListV1GetItemAttributesGet(params *CatalogProductLinkTypeListV1GetItemAttributesGetParams, opts ...ClientOption) (*CatalogProductLinkTypeListV1GetItemAttributesGetOK, error)

	CatalogProductLinkTypeListV1GetItemsGet(params *CatalogProductLinkTypeListV1GetItemsGetParams, opts ...ClientOption) (*CatalogProductLinkTypeListV1GetItemsGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CatalogProductLinkTypeListV1GetItemAttributesGet Provide a list of the product link type attributes
*/
func (a *Client) CatalogProductLinkTypeListV1GetItemAttributesGet(params *CatalogProductLinkTypeListV1GetItemAttributesGetParams, opts ...ClientOption) (*CatalogProductLinkTypeListV1GetItemAttributesGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogProductLinkTypeListV1GetItemAttributesGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogProductLinkTypeListV1GetItemAttributesGet",
		Method:             "GET",
		PathPattern:        "/V1/products/links/{type}/attributes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogProductLinkTypeListV1GetItemAttributesGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogProductLinkTypeListV1GetItemAttributesGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogProductLinkTypeListV1GetItemAttributesGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  CatalogProductLinkTypeListV1GetItemsGet Retrieve information about available product link types
*/
func (a *Client) CatalogProductLinkTypeListV1GetItemsGet(params *CatalogProductLinkTypeListV1GetItemsGetParams, opts ...ClientOption) (*CatalogProductLinkTypeListV1GetItemsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogProductLinkTypeListV1GetItemsGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogProductLinkTypeListV1GetItemsGet",
		Method:             "GET",
		PathPattern:        "/V1/products/links/types",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogProductLinkTypeListV1GetItemsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogProductLinkTypeListV1GetItemsGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogProductLinkTypeListV1GetItemsGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
