// Code generated by go-swagger; DO NOT EDIT.

package checkout_guest_payment_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new checkout guest payment information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for checkout guest payment information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGet(params *CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetOK, error)

	CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostOK, error)

	CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGet Get payment information
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGet(params *CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1GetPaymentInformationGet",
		Method:             "GET",
		PathPattern:        "/V1/guest-carts/{cartId}/payment-information",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost Set payment information and place order for a specified cart.
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/payment-information",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPost Set payment information for a specified cart.
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostParams, opts ...ClientOption) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1SavePaymentInformationPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/set-payment-information",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
