// Code generated by go-swagger; DO NOT EDIT.

package catalog_product_attribute_option_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// CatalogProductAttributeOptionManagementV1GetItemsGetReader is a Reader for the CatalogProductAttributeOptionManagementV1GetItemsGet structure.
type CatalogProductAttributeOptionManagementV1GetItemsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CatalogProductAttributeOptionManagementV1GetItemsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCatalogProductAttributeOptionManagementV1GetItemsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCatalogProductAttributeOptionManagementV1GetItemsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCatalogProductAttributeOptionManagementV1GetItemsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCatalogProductAttributeOptionManagementV1GetItemsGetOK creates a CatalogProductAttributeOptionManagementV1GetItemsGetOK with default headers values
func NewCatalogProductAttributeOptionManagementV1GetItemsGetOK() *CatalogProductAttributeOptionManagementV1GetItemsGetOK {
	return &CatalogProductAttributeOptionManagementV1GetItemsGetOK{}
}

/* CatalogProductAttributeOptionManagementV1GetItemsGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type CatalogProductAttributeOptionManagementV1GetItemsGetOK struct {
	Payload []*models.EavDataAttributeOptionInterface
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/products/attributes/{attributeCode}/options][%d] catalogProductAttributeOptionManagementV1GetItemsGetOK  %+v", 200, o.Payload)
}
func (o *CatalogProductAttributeOptionManagementV1GetItemsGetOK) GetPayload() []*models.EavDataAttributeOptionInterface {
	return o.Payload
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogProductAttributeOptionManagementV1GetItemsGetBadRequest creates a CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest with default headers values
func NewCatalogProductAttributeOptionManagementV1GetItemsGetBadRequest() *CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest {
	return &CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest{}
}

/* CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest describes a response with status code 400, with default header values.

400 Bad Request
*/
type CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/products/attributes/{attributeCode}/options][%d] catalogProductAttributeOptionManagementV1GetItemsGetBadRequest  %+v", 400, o.Payload)
}
func (o *CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogProductAttributeOptionManagementV1GetItemsGetDefault creates a CatalogProductAttributeOptionManagementV1GetItemsGetDefault with default headers values
func NewCatalogProductAttributeOptionManagementV1GetItemsGetDefault(code int) *CatalogProductAttributeOptionManagementV1GetItemsGetDefault {
	return &CatalogProductAttributeOptionManagementV1GetItemsGetDefault{
		_statusCode: code,
	}
}

/* CatalogProductAttributeOptionManagementV1GetItemsGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type CatalogProductAttributeOptionManagementV1GetItemsGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the catalog product attribute option management v1 get items get default response
func (o *CatalogProductAttributeOptionManagementV1GetItemsGetDefault) Code() int {
	return o._statusCode
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/products/attributes/{attributeCode}/options][%d] catalogProductAttributeOptionManagementV1GetItemsGet default  %+v", o._statusCode, o.Payload)
}
func (o *CatalogProductAttributeOptionManagementV1GetItemsGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CatalogProductAttributeOptionManagementV1GetItemsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
