// Code generated by go-swagger; DO NOT EDIT.

package directory_country_information_acquirer_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new directory country information acquirer v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for directory country information acquirer v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DirectoryCountryInformationAcquirerV1GetCountriesInfoGet(params *DirectoryCountryInformationAcquirerV1GetCountriesInfoGetParams, opts ...ClientOption) (*DirectoryCountryInformationAcquirerV1GetCountriesInfoGetOK, error)

	DirectoryCountryInformationAcquirerV1GetCountryInfoGet(params *DirectoryCountryInformationAcquirerV1GetCountryInfoGetParams, opts ...ClientOption) (*DirectoryCountryInformationAcquirerV1GetCountryInfoGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DirectoryCountryInformationAcquirerV1GetCountriesInfoGet Get all countries and regions information for the store.
*/
func (a *Client) DirectoryCountryInformationAcquirerV1GetCountriesInfoGet(params *DirectoryCountryInformationAcquirerV1GetCountriesInfoGetParams, opts ...ClientOption) (*DirectoryCountryInformationAcquirerV1GetCountriesInfoGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectoryCountryInformationAcquirerV1GetCountriesInfoGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "directoryCountryInformationAcquirerV1GetCountriesInfoGet",
		Method:             "GET",
		PathPattern:        "/V1/directory/countries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DirectoryCountryInformationAcquirerV1GetCountriesInfoGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DirectoryCountryInformationAcquirerV1GetCountriesInfoGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DirectoryCountryInformationAcquirerV1GetCountriesInfoGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  DirectoryCountryInformationAcquirerV1GetCountryInfoGet Get country and region information for the store.
*/
func (a *Client) DirectoryCountryInformationAcquirerV1GetCountryInfoGet(params *DirectoryCountryInformationAcquirerV1GetCountryInfoGetParams, opts ...ClientOption) (*DirectoryCountryInformationAcquirerV1GetCountryInfoGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectoryCountryInformationAcquirerV1GetCountryInfoGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "directoryCountryInformationAcquirerV1GetCountryInfoGet",
		Method:             "GET",
		PathPattern:        "/V1/directory/countries/{countryId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DirectoryCountryInformationAcquirerV1GetCountryInfoGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DirectoryCountryInformationAcquirerV1GetCountryInfoGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DirectoryCountryInformationAcquirerV1GetCountryInfoGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
