// Code generated by go-swagger; DO NOT EDIT.

package pay_pal_braintree_auth_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// PayPalBraintreeAuthV1GetGetReader is a Reader for the PayPalBraintreeAuthV1GetGet structure.
type PayPalBraintreeAuthV1GetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PayPalBraintreeAuthV1GetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPayPalBraintreeAuthV1GetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPayPalBraintreeAuthV1GetGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPayPalBraintreeAuthV1GetGetOK creates a PayPalBraintreeAuthV1GetGetOK with default headers values
func NewPayPalBraintreeAuthV1GetGetOK() *PayPalBraintreeAuthV1GetGetOK {
	return &PayPalBraintreeAuthV1GetGetOK{}
}

/* PayPalBraintreeAuthV1GetGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type PayPalBraintreeAuthV1GetGetOK struct {
	Payload *models.PayPalBraintreeDataAuthDataInterface
}

func (o *PayPalBraintreeAuthV1GetGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/applepay/auth][%d] payPalBraintreeAuthV1GetGetOK  %+v", 200, o.Payload)
}
func (o *PayPalBraintreeAuthV1GetGetOK) GetPayload() *models.PayPalBraintreeDataAuthDataInterface {
	return o.Payload
}

func (o *PayPalBraintreeAuthV1GetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PayPalBraintreeDataAuthDataInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPayPalBraintreeAuthV1GetGetDefault creates a PayPalBraintreeAuthV1GetGetDefault with default headers values
func NewPayPalBraintreeAuthV1GetGetDefault(code int) *PayPalBraintreeAuthV1GetGetDefault {
	return &PayPalBraintreeAuthV1GetGetDefault{
		_statusCode: code,
	}
}

/* PayPalBraintreeAuthV1GetGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PayPalBraintreeAuthV1GetGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the pay pal braintree auth v1 get get default response
func (o *PayPalBraintreeAuthV1GetGetDefault) Code() int {
	return o._statusCode
}

func (o *PayPalBraintreeAuthV1GetGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/applepay/auth][%d] payPalBraintreeAuthV1GetGet default  %+v", o._statusCode, o.Payload)
}
func (o *PayPalBraintreeAuthV1GetGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PayPalBraintreeAuthV1GetGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
