// Code generated by go-swagger; DO NOT EDIT.

package catalog_product_type_list_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new catalog product type list v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog product type list v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CatalogProductTypeListV1GetProductTypesGet(params *CatalogProductTypeListV1GetProductTypesGetParams, opts ...ClientOption) (*CatalogProductTypeListV1GetProductTypesGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CatalogProductTypeListV1GetProductTypesGet Retrieve available product types
*/
func (a *Client) CatalogProductTypeListV1GetProductTypesGet(params *CatalogProductTypeListV1GetProductTypesGetParams, opts ...ClientOption) (*CatalogProductTypeListV1GetProductTypesGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogProductTypeListV1GetProductTypesGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogProductTypeListV1GetProductTypesGet",
		Method:             "GET",
		PathPattern:        "/V1/products/types",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogProductTypeListV1GetProductTypesGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogProductTypeListV1GetProductTypesGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogProductTypeListV1GetProductTypesGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
