// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_payment_method_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// QuoteGuestPaymentMethodManagementV1GetListGetReader is a Reader for the QuoteGuestPaymentMethodManagementV1GetListGet structure.
type QuoteGuestPaymentMethodManagementV1GetListGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuoteGuestPaymentMethodManagementV1GetListGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQuoteGuestPaymentMethodManagementV1GetListGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewQuoteGuestPaymentMethodManagementV1GetListGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewQuoteGuestPaymentMethodManagementV1GetListGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQuoteGuestPaymentMethodManagementV1GetListGetOK creates a QuoteGuestPaymentMethodManagementV1GetListGetOK with default headers values
func NewQuoteGuestPaymentMethodManagementV1GetListGetOK() *QuoteGuestPaymentMethodManagementV1GetListGetOK {
	return &QuoteGuestPaymentMethodManagementV1GetListGetOK{}
}

/* QuoteGuestPaymentMethodManagementV1GetListGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type QuoteGuestPaymentMethodManagementV1GetListGetOK struct {
	Payload []*models.QuoteDataPaymentMethodInterface
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/guest-carts/{cartId}/payment-methods][%d] quoteGuestPaymentMethodManagementV1GetListGetOK  %+v", 200, o.Payload)
}
func (o *QuoteGuestPaymentMethodManagementV1GetListGetOK) GetPayload() []*models.QuoteDataPaymentMethodInterface {
	return o.Payload
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteGuestPaymentMethodManagementV1GetListGetBadRequest creates a QuoteGuestPaymentMethodManagementV1GetListGetBadRequest with default headers values
func NewQuoteGuestPaymentMethodManagementV1GetListGetBadRequest() *QuoteGuestPaymentMethodManagementV1GetListGetBadRequest {
	return &QuoteGuestPaymentMethodManagementV1GetListGetBadRequest{}
}

/* QuoteGuestPaymentMethodManagementV1GetListGetBadRequest describes a response with status code 400, with default header values.

400 Bad Request
*/
type QuoteGuestPaymentMethodManagementV1GetListGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/guest-carts/{cartId}/payment-methods][%d] quoteGuestPaymentMethodManagementV1GetListGetBadRequest  %+v", 400, o.Payload)
}
func (o *QuoteGuestPaymentMethodManagementV1GetListGetBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteGuestPaymentMethodManagementV1GetListGetDefault creates a QuoteGuestPaymentMethodManagementV1GetListGetDefault with default headers values
func NewQuoteGuestPaymentMethodManagementV1GetListGetDefault(code int) *QuoteGuestPaymentMethodManagementV1GetListGetDefault {
	return &QuoteGuestPaymentMethodManagementV1GetListGetDefault{
		_statusCode: code,
	}
}

/* QuoteGuestPaymentMethodManagementV1GetListGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type QuoteGuestPaymentMethodManagementV1GetListGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the quote guest payment method management v1 get list get default response
func (o *QuoteGuestPaymentMethodManagementV1GetListGetDefault) Code() int {
	return o._statusCode
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/guest-carts/{cartId}/payment-methods][%d] quoteGuestPaymentMethodManagementV1GetListGet default  %+v", o._statusCode, o.Payload)
}
func (o *QuoteGuestPaymentMethodManagementV1GetListGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *QuoteGuestPaymentMethodManagementV1GetListGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
