// Code generated by go-swagger; DO NOT EDIT.

package gift_message_guest_cart_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new gift message guest cart repository v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for gift message guest cart repository v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GiftMessageGuestCartRepositoryV1GetGet(params *GiftMessageGuestCartRepositoryV1GetGetParams, opts ...ClientOption) (*GiftMessageGuestCartRepositoryV1GetGetOK, error)

	GiftMessageGuestCartRepositoryV1SavePost(params *GiftMessageGuestCartRepositoryV1SavePostParams, opts ...ClientOption) (*GiftMessageGuestCartRepositoryV1SavePostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GiftMessageGuestCartRepositoryV1GetGet Return the gift message for a specified order.
*/
func (a *Client) GiftMessageGuestCartRepositoryV1GetGet(params *GiftMessageGuestCartRepositoryV1GetGetParams, opts ...ClientOption) (*GiftMessageGuestCartRepositoryV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGiftMessageGuestCartRepositoryV1GetGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "giftMessageGuestCartRepositoryV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/guest-carts/{cartId}/gift-message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GiftMessageGuestCartRepositoryV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GiftMessageGuestCartRepositoryV1GetGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GiftMessageGuestCartRepositoryV1GetGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GiftMessageGuestCartRepositoryV1SavePost Set the gift message for an entire order.
*/
func (a *Client) GiftMessageGuestCartRepositoryV1SavePost(params *GiftMessageGuestCartRepositoryV1SavePostParams, opts ...ClientOption) (*GiftMessageGuestCartRepositoryV1SavePostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGiftMessageGuestCartRepositoryV1SavePostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "giftMessageGuestCartRepositoryV1SavePost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/gift-message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GiftMessageGuestCartRepositoryV1SavePostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GiftMessageGuestCartRepositoryV1SavePostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GiftMessageGuestCartRepositoryV1SavePostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
