// Code generated by go-swagger; DO NOT EDIT.

package configurable_product_option_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new configurable product option repository v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for configurable product option repository v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ConfigurableProductOptionRepositoryV1GetGet(params *ConfigurableProductOptionRepositoryV1GetGetParams, opts ...ClientOption) (*ConfigurableProductOptionRepositoryV1GetGetOK, error)

	ConfigurableProductOptionRepositoryV1GetListGet(params *ConfigurableProductOptionRepositoryV1GetListGetParams, opts ...ClientOption) (*ConfigurableProductOptionRepositoryV1GetListGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ConfigurableProductOptionRepositoryV1GetGet Get option for configurable product
*/
func (a *Client) ConfigurableProductOptionRepositoryV1GetGet(params *ConfigurableProductOptionRepositoryV1GetGetParams, opts ...ClientOption) (*ConfigurableProductOptionRepositoryV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConfigurableProductOptionRepositoryV1GetGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "configurableProductOptionRepositoryV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/configurable-products/{sku}/options/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ConfigurableProductOptionRepositoryV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConfigurableProductOptionRepositoryV1GetGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ConfigurableProductOptionRepositoryV1GetGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ConfigurableProductOptionRepositoryV1GetListGet Get all options for configurable product
*/
func (a *Client) ConfigurableProductOptionRepositoryV1GetListGet(params *ConfigurableProductOptionRepositoryV1GetListGetParams, opts ...ClientOption) (*ConfigurableProductOptionRepositoryV1GetListGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConfigurableProductOptionRepositoryV1GetListGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "configurableProductOptionRepositoryV1GetListGet",
		Method:             "GET",
		PathPattern:        "/V1/configurable-products/{sku}/options/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ConfigurableProductOptionRepositoryV1GetListGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConfigurableProductOptionRepositoryV1GetListGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ConfigurableProductOptionRepositoryV1GetListGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
