// Code generated by go-swagger; DO NOT EDIT.

package vertex_address_validation_address_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVertexAddressValidationAddressManagementV1GetValidAddressPostParams creates a new VertexAddressValidationAddressManagementV1GetValidAddressPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVertexAddressValidationAddressManagementV1GetValidAddressPostParams() *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	return &VertexAddressValidationAddressManagementV1GetValidAddressPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithTimeout creates a new VertexAddressValidationAddressManagementV1GetValidAddressPostParams object
// with the ability to set a timeout on a request.
func NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithTimeout(timeout time.Duration) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	return &VertexAddressValidationAddressManagementV1GetValidAddressPostParams{
		timeout: timeout,
	}
}

// NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithContext creates a new VertexAddressValidationAddressManagementV1GetValidAddressPostParams object
// with the ability to set a context for a request.
func NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithContext(ctx context.Context) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	return &VertexAddressValidationAddressManagementV1GetValidAddressPostParams{
		Context: ctx,
	}
}

// NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithHTTPClient creates a new VertexAddressValidationAddressManagementV1GetValidAddressPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewVertexAddressValidationAddressManagementV1GetValidAddressPostParamsWithHTTPClient(client *http.Client) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	return &VertexAddressValidationAddressManagementV1GetValidAddressPostParams{
		HTTPClient: client,
	}
}

/* VertexAddressValidationAddressManagementV1GetValidAddressPostParams contains all the parameters to send to the API endpoint
   for the vertex address validation address management v1 get valid address post operation.

   Typically these are written to a http.Request.
*/
type VertexAddressValidationAddressManagementV1GetValidAddressPostParams struct {

	// VertexAddressValidationAddressManagementV1GetValidAddressPostBody.
	VertexAddressValidationAddressManagementV1GetValidAddressPostBody VertexAddressValidationAddressManagementV1GetValidAddressPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vertex address validation address management v1 get valid address post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WithDefaults() *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vertex address validation address management v1 get valid address post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WithTimeout(timeout time.Duration) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WithContext(ctx context.Context) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WithHTTPClient(client *http.Client) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVertexAddressValidationAddressManagementV1GetValidAddressPostBody adds the vertexAddressValidationAddressManagementV1GetValidAddressPostBody to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WithVertexAddressValidationAddressManagementV1GetValidAddressPostBody(vertexAddressValidationAddressManagementV1GetValidAddressPostBody VertexAddressValidationAddressManagementV1GetValidAddressPostBody) *VertexAddressValidationAddressManagementV1GetValidAddressPostParams {
	o.SetVertexAddressValidationAddressManagementV1GetValidAddressPostBody(vertexAddressValidationAddressManagementV1GetValidAddressPostBody)
	return o
}

// SetVertexAddressValidationAddressManagementV1GetValidAddressPostBody adds the vertexAddressValidationAddressManagementV1GetValidAddressPostBody to the vertex address validation address management v1 get valid address post params
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) SetVertexAddressValidationAddressManagementV1GetValidAddressPostBody(vertexAddressValidationAddressManagementV1GetValidAddressPostBody VertexAddressValidationAddressManagementV1GetValidAddressPostBody) {
	o.VertexAddressValidationAddressManagementV1GetValidAddressPostBody = vertexAddressValidationAddressManagementV1GetValidAddressPostBody
}

// WriteToRequest writes these params to a swagger request
func (o *VertexAddressValidationAddressManagementV1GetValidAddressPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.VertexAddressValidationAddressManagementV1GetValidAddressPostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
