// Code generated by go-swagger; DO NOT EDIT.

package checkout_guest_shipping_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new checkout guest shipping information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for checkout guest shipping information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CheckoutGuestShippingInformationManagementV1SaveAddressInformationPost(params *CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostParams, opts ...ClientOption) (*CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CheckoutGuestShippingInformationManagementV1SaveAddressInformationPost checkout guest shipping information management v1 save address information post API
*/
func (a *Client) CheckoutGuestShippingInformationManagementV1SaveAddressInformationPost(params *CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostParams, opts ...ClientOption) (*CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestShippingInformationManagementV1SaveAddressInformationPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkoutGuestShippingInformationManagementV1SaveAddressInformationPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/shipping-information",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
