// Code generated by go-swagger; DO NOT EDIT.

package integration_customer_token_service_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new integration customer token service v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for integration customer token service v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPost(params *IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostParams, opts ...ClientOption) (*IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPost Create access token for admin given the customer credentials.
*/
func (a *Client) IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPost(params *IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostParams, opts ...ClientOption) (*IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "integrationCustomerTokenServiceV1CreateCustomerAccessTokenPost",
		Method:             "POST",
		PathPattern:        "/V1/integration/customer/token",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*IntegrationCustomerTokenServiceV1CreateCustomerAccessTokenPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
