// Code generated by go-swagger; DO NOT EDIT.

package checkout_guest_totals_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new checkout guest totals information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for checkout guest totals information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CheckoutGuestTotalsInformationManagementV1CalculatePost(params *CheckoutGuestTotalsInformationManagementV1CalculatePostParams, opts ...ClientOption) (*CheckoutGuestTotalsInformationManagementV1CalculatePostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CheckoutGuestTotalsInformationManagementV1CalculatePost Calculate quote totals based on address and shipping method.
*/
func (a *Client) CheckoutGuestTotalsInformationManagementV1CalculatePost(params *CheckoutGuestTotalsInformationManagementV1CalculatePostParams, opts ...ClientOption) (*CheckoutGuestTotalsInformationManagementV1CalculatePostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestTotalsInformationManagementV1CalculatePostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "checkoutGuestTotalsInformationManagementV1CalculatePost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/totals-information",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CheckoutGuestTotalsInformationManagementV1CalculatePostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckoutGuestTotalsInformationManagementV1CalculatePostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CheckoutGuestTotalsInformationManagementV1CalculatePostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
