// Code generated by go-swagger; DO NOT EDIT.

package amazon_payment_order_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new amazon payment order information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for amazon payment order information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDelete(params *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams, opts ...ClientOption) error

	SetTransport(transport runtime.ClientTransport)
}

/*
  AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDelete amazon payment order information management v1 remove order reference delete API
*/
func (a *Client) AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDelete(params *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "amazonPaymentOrderInformationManagementV1RemoveOrderReferenceDelete",
		Method:             "DELETE",
		PathPattern:        "/V1/amazon/order-ref",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
