// Code generated by go-swagger; DO NOT EDIT.

package amazon_payment_order_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams creates a new AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams() *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	return &AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithTimeout creates a new AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams object
// with the ability to set a timeout on a request.
func NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithTimeout(timeout time.Duration) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	return &AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams{
		timeout: timeout,
	}
}

// NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithContext creates a new AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams object
// with the ability to set a context for a request.
func NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithContext(ctx context.Context) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	return &AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams{
		Context: ctx,
	}
}

// NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithHTTPClient creates a new AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParamsWithHTTPClient(client *http.Client) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	return &AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams{
		HTTPClient: client,
	}
}

/* AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams contains all the parameters to send to the API endpoint
   for the amazon payment order information management v1 remove order reference delete operation.

   Typically these are written to a http.Request.
*/
type AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the amazon payment order information management v1 remove order reference delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) WithDefaults() *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the amazon payment order information management v1 remove order reference delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) WithTimeout(timeout time.Duration) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) WithContext(ctx context.Context) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) WithHTTPClient(client *http.Client) *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the amazon payment order information management v1 remove order reference delete params
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AmazonPaymentOrderInformationManagementV1RemoveOrderReferenceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
