// Code generated by go-swagger; DO NOT EDIT.

package catalog_attribute_set_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new catalog attribute set repository v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog attribute set repository v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CatalogAttributeSetRepositoryV1GetGet(params *CatalogAttributeSetRepositoryV1GetGetParams, opts ...ClientOption) (*CatalogAttributeSetRepositoryV1GetGetOK, error)

	CatalogAttributeSetRepositoryV1GetListGet(params *CatalogAttributeSetRepositoryV1GetListGetParams, opts ...ClientOption) (*CatalogAttributeSetRepositoryV1GetListGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CatalogAttributeSetRepositoryV1GetGet Retrieve attribute set information based on given ID
*/
func (a *Client) CatalogAttributeSetRepositoryV1GetGet(params *CatalogAttributeSetRepositoryV1GetGetParams, opts ...ClientOption) (*CatalogAttributeSetRepositoryV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogAttributeSetRepositoryV1GetGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogAttributeSetRepositoryV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/products/attribute-sets/{attributeSetId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogAttributeSetRepositoryV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogAttributeSetRepositoryV1GetGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogAttributeSetRepositoryV1GetGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  CatalogAttributeSetRepositoryV1GetListGet Retrieve list of Attribute Sets
*/
func (a *Client) CatalogAttributeSetRepositoryV1GetListGet(params *CatalogAttributeSetRepositoryV1GetListGetParams, opts ...ClientOption) (*CatalogAttributeSetRepositoryV1GetListGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogAttributeSetRepositoryV1GetListGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogAttributeSetRepositoryV1GetListGet",
		Method:             "GET",
		PathPattern:        "/V1/products/attribute-sets/sets/list",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogAttributeSetRepositoryV1GetListGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogAttributeSetRepositoryV1GetListGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogAttributeSetRepositoryV1GetListGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
