// Code generated by go-swagger; DO NOT EDIT.

package vertex_address_validation_api_guest_cleanse_address_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new vertex address validation api guest cleanse address v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for vertex address validation api guest cleanse address v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPost(params *VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostParams, opts ...ClientOption) (*VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPost Query Vertex to cleanse an address
*/
func (a *Client) VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPost(params *VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostParams, opts ...ClientOption) (*VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "vertexAddressValidationApiGuestCleanseAddressV1CleanseAddressPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-address/cleanse",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*VertexAddressValidationAPIGuestCleanseAddressV1CleanseAddressPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
