// Code generated by go-swagger; DO NOT EDIT.

package cms_page_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new cms page repository v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cms page repository v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CmsPageRepositoryV1GetByIDGet(params *CmsPageRepositoryV1GetByIDGetParams, opts ...ClientOption) (*CmsPageRepositoryV1GetByIDGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CmsPageRepositoryV1GetByIDGet Retrieve page.
*/
func (a *Client) CmsPageRepositoryV1GetByIDGet(params *CmsPageRepositoryV1GetByIDGetParams, opts ...ClientOption) (*CmsPageRepositoryV1GetByIDGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCmsPageRepositoryV1GetByIDGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "cmsPageRepositoryV1GetByIdGet",
		Method:             "GET",
		PathPattern:        "/V1/cmsPage/{pageId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CmsPageRepositoryV1GetByIDGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CmsPageRepositoryV1GetByIDGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CmsPageRepositoryV1GetByIDGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
