// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_coupon_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQuoteGuestCouponManagementV1RemoveDeleteParams creates a new QuoteGuestCouponManagementV1RemoveDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQuoteGuestCouponManagementV1RemoveDeleteParams() *QuoteGuestCouponManagementV1RemoveDeleteParams {
	return &QuoteGuestCouponManagementV1RemoveDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithTimeout creates a new QuoteGuestCouponManagementV1RemoveDeleteParams object
// with the ability to set a timeout on a request.
func NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithTimeout(timeout time.Duration) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	return &QuoteGuestCouponManagementV1RemoveDeleteParams{
		timeout: timeout,
	}
}

// NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithContext creates a new QuoteGuestCouponManagementV1RemoveDeleteParams object
// with the ability to set a context for a request.
func NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithContext(ctx context.Context) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	return &QuoteGuestCouponManagementV1RemoveDeleteParams{
		Context: ctx,
	}
}

// NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithHTTPClient creates a new QuoteGuestCouponManagementV1RemoveDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewQuoteGuestCouponManagementV1RemoveDeleteParamsWithHTTPClient(client *http.Client) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	return &QuoteGuestCouponManagementV1RemoveDeleteParams{
		HTTPClient: client,
	}
}

/* QuoteGuestCouponManagementV1RemoveDeleteParams contains all the parameters to send to the API endpoint
   for the quote guest coupon management v1 remove delete operation.

   Typically these are written to a http.Request.
*/
type QuoteGuestCouponManagementV1RemoveDeleteParams struct {

	/* CartID.

	   The cart ID.
	*/
	CartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the quote guest coupon management v1 remove delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WithDefaults() *QuoteGuestCouponManagementV1RemoveDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the quote guest coupon management v1 remove delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WithTimeout(timeout time.Duration) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WithContext(ctx context.Context) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WithHTTPClient(client *http.Client) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCartID adds the cartID to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WithCartID(cartID string) *QuoteGuestCouponManagementV1RemoveDeleteParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the quote guest coupon management v1 remove delete params
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) SetCartID(cartID string) {
	o.CartID = cartID
}

// WriteToRequest writes these params to a swagger request
func (o *QuoteGuestCouponManagementV1RemoveDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cartId
	if err := r.SetPathParam("cartId", o.CartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
