// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_billing_address_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new quote guest billing address management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for quote guest billing address management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	QuoteGuestBillingAddressManagementV1AssignPost(params *QuoteGuestBillingAddressManagementV1AssignPostParams, opts ...ClientOption) (*QuoteGuestBillingAddressManagementV1AssignPostOK, error)

	QuoteGuestBillingAddressManagementV1GetGet(params *QuoteGuestBillingAddressManagementV1GetGetParams, opts ...ClientOption) (*QuoteGuestBillingAddressManagementV1GetGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  QuoteGuestBillingAddressManagementV1AssignPost Assign a specified billing address to a specified cart.
*/
func (a *Client) QuoteGuestBillingAddressManagementV1AssignPost(params *QuoteGuestBillingAddressManagementV1AssignPostParams, opts ...ClientOption) (*QuoteGuestBillingAddressManagementV1AssignPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteGuestBillingAddressManagementV1AssignPostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "quoteGuestBillingAddressManagementV1AssignPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/billing-address",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &QuoteGuestBillingAddressManagementV1AssignPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QuoteGuestBillingAddressManagementV1AssignPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*QuoteGuestBillingAddressManagementV1AssignPostDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  QuoteGuestBillingAddressManagementV1GetGet Return the billing address for a specified quote.
*/
func (a *Client) QuoteGuestBillingAddressManagementV1GetGet(params *QuoteGuestBillingAddressManagementV1GetGetParams, opts ...ClientOption) (*QuoteGuestBillingAddressManagementV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteGuestBillingAddressManagementV1GetGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "quoteGuestBillingAddressManagementV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/guest-carts/{cartId}/billing-address",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &QuoteGuestBillingAddressManagementV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QuoteGuestBillingAddressManagementV1GetGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*QuoteGuestBillingAddressManagementV1GetGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
