// Code generated by go-swagger; DO NOT EDIT.

package inventory_in_store_pickup_api_get_pickup_locations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new inventory in store pickup api get pickup locations v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for inventory in store pickup api get pickup locations v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGet(params *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetParams, opts ...ClientOption) (*InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGet Get Pickup Locations according to the results of filtration by Search Request.
*/
func (a *Client) InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGet(params *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetParams, opts ...ClientOption) (*InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "inventoryInStorePickupApiGetPickupLocationsV1ExecuteGet",
		Method:             "GET",
		PathPattern:        "/V1/inventory/in-store-pickup/pickup-locations/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
