// Code generated by go-swagger; DO NOT EDIT.

package inventory_in_store_pickup_api_get_pickup_locations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/localrivet/magento2go/models"
)

// InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetReader is a Reader for the InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGet structure.
type InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK creates a InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK with default headers values
func NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK() *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK {
	return &InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK{}
}

/* InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK describes a response with status code 200, with default header values.

200 Success.
*/
type InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK struct {
	Payload *models.InventoryInStorePickupAPIDataSearchResultInterface
}

func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/inventory/in-store-pickup/pickup-locations/][%d] inventoryInStorePickupApiGetPickupLocationsV1ExecuteGetOK  %+v", 200, o.Payload)
}
func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK) GetPayload() *models.InventoryInStorePickupAPIDataSearchResultInterface {
	return o.Payload
}

func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryInStorePickupAPIDataSearchResultInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault creates a InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault with default headers values
func NewInventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault(code int) *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault {
	return &InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault{
		_statusCode: code,
	}
}

/* InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the inventory in store pickup Api get pickup locations v1 execute get default response
func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault) Code() int {
	return o._statusCode
}

func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/inventory/in-store-pickup/pickup-locations/][%d] inventoryInStorePickupApiGetPickupLocationsV1ExecuteGet default  %+v", o._statusCode, o.Payload)
}
func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *InventoryInStorePickupAPIGetPickupLocationsV1ExecuteGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
