// Code generated by go-swagger; DO NOT EDIT.

package catalog_category_link_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new catalog category link management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog category link management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CatalogCategoryLinkManagementV1GetAssignedProductsGet(params *CatalogCategoryLinkManagementV1GetAssignedProductsGetParams, opts ...ClientOption) (*CatalogCategoryLinkManagementV1GetAssignedProductsGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CatalogCategoryLinkManagementV1GetAssignedProductsGet Get products assigned to category
*/
func (a *Client) CatalogCategoryLinkManagementV1GetAssignedProductsGet(params *CatalogCategoryLinkManagementV1GetAssignedProductsGetParams, opts ...ClientOption) (*CatalogCategoryLinkManagementV1GetAssignedProductsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCatalogCategoryLinkManagementV1GetAssignedProductsGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "catalogCategoryLinkManagementV1GetAssignedProductsGet",
		Method:             "GET",
		PathPattern:        "/V1/categories/{categoryId}/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CatalogCategoryLinkManagementV1GetAssignedProductsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CatalogCategoryLinkManagementV1GetAssignedProductsGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CatalogCategoryLinkManagementV1GetAssignedProductsGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
