// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorErrorsItem Error details
//
// swagger:model error-errors-item
type ErrorErrorsItem struct {

	// Error message
	Message string `json:"message,omitempty"`

	// parameters
	Parameters ErrorParameters `json:"parameters,omitempty"`
}

// Validate validates this error errors item
func (m *ErrorErrorsItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorErrorsItem) validateParameters(formats strfmt.Registry) error {
	if swag.IsZero(m.Parameters) { // not required
		return nil
	}

	if err := m.Parameters.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("parameters")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("parameters")
		}
		return err
	}

	return nil
}

// ContextValidate validate this error errors item based on the context it is used
func (m *ErrorErrorsItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorErrorsItem) contextValidateParameters(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Parameters.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("parameters")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("parameters")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ErrorErrorsItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorErrorsItem) UnmarshalBinary(b []byte) error {
	var res ErrorErrorsItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
