// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GroupedProductDataGroupedOptionsExtensionInterface ExtensionInterface class for @see \Magento\GroupedProduct\Api\Data\GroupedOptionsInterface
//
// swagger:model grouped-product-data-grouped-options-extension-interface
type GroupedProductDataGroupedOptionsExtensionInterface interface{}
