// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryInStorePickupAPIDataSearchRequestFilterInterface Filter for Pickup Location search.
//
// swagger:model inventory-in-store-pickup-api-data-search-request-filter-interface
type InventoryInStorePickupAPIDataSearchRequestFilterInterface struct {

	// Condition Type.
	// Required: true
	ConditionType *string `json:"condition_type"`

	// Value.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this inventory in store pickup api data search request filter interface
func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) validateConditionType(formats strfmt.Registry) error {

	if err := validate.Required("condition_type", "body", m.ConditionType); err != nil {
		return err
	}

	return nil
}

func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this inventory in store pickup api data search request filter interface based on context it is used
func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryInStorePickupAPIDataSearchRequestFilterInterface) UnmarshalBinary(b []byte) error {
	var res InventoryInStorePickupAPIDataSearchRequestFilterInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
