// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryInStorePickupAPIDataSearchRequestExtensionInterface ExtensionInterface class for @see \Magento\InventoryInStorePickupApi\Api\Data\SearchRequestInterface
//
// swagger:model inventory-in-store-pickup-api-data-search-request-extension-interface
type InventoryInStorePickupAPIDataSearchRequestExtensionInterface struct {

	// products info
	ProductsInfo []*InventoryInStorePickupAPIDataSearchRequestProductInfoInterface `json:"products_info"`
}

// Validate validates this inventory in store pickup api data search request extension interface
func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProductsInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) validateProductsInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.ProductsInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.ProductsInfo); i++ {
		if swag.IsZero(m.ProductsInfo[i]) { // not required
			continue
		}

		if m.ProductsInfo[i] != nil {
			if err := m.ProductsInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("products_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("products_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inventory in store pickup api data search request extension interface based on the context it is used
func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProductsInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) contextValidateProductsInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ProductsInfo); i++ {

		if m.ProductsInfo[i] != nil {
			if err := m.ProductsInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("products_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("products_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryInStorePickupAPIDataSearchRequestExtensionInterface) UnmarshalBinary(b []byte) error {
	var res InventoryInStorePickupAPIDataSearchRequestExtensionInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
