// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// InventoryInStorePickupAPIDataSearchRequestProductInfoExtensionInterface ExtensionInterface class for @see \Magento\InventoryInStorePickupApi\Api\Data\SearchRequest\ProductInfoInterface
//
// swagger:model inventory-in-store-pickup-api-data-search-request-product-info-extension-interface
type InventoryInStorePickupAPIDataSearchRequestProductInfoExtensionInterface interface{}
