// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuoteDataCartExtensionInterface ExtensionInterface class for @see \Magento\Quote\Api\Data\CartInterface
//
// swagger:model quote-data-cart-extension-interface
type QuoteDataCartExtensionInterface struct {

	// amazon order reference id
	AmazonOrderReferenceID *AmazonPaymentDataQuoteLinkInterface `json:"amazon_order_reference_id,omitempty"`

	// shipping assignments
	ShippingAssignments []*QuoteDataShippingAssignmentInterface `json:"shipping_assignments"`
}

// Validate validates this quote data cart extension interface
func (m *QuoteDataCartExtensionInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmazonOrderReferenceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShippingAssignments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuoteDataCartExtensionInterface) validateAmazonOrderReferenceID(formats strfmt.Registry) error {
	if swag.IsZero(m.AmazonOrderReferenceID) { // not required
		return nil
	}

	if m.AmazonOrderReferenceID != nil {
		if err := m.AmazonOrderReferenceID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amazon_order_reference_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amazon_order_reference_id")
			}
			return err
		}
	}

	return nil
}

func (m *QuoteDataCartExtensionInterface) validateShippingAssignments(formats strfmt.Registry) error {
	if swag.IsZero(m.ShippingAssignments) { // not required
		return nil
	}

	for i := 0; i < len(m.ShippingAssignments); i++ {
		if swag.IsZero(m.ShippingAssignments[i]) { // not required
			continue
		}

		if m.ShippingAssignments[i] != nil {
			if err := m.ShippingAssignments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shipping_assignments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shipping_assignments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this quote data cart extension interface based on the context it is used
func (m *QuoteDataCartExtensionInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmazonOrderReferenceID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateShippingAssignments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuoteDataCartExtensionInterface) contextValidateAmazonOrderReferenceID(ctx context.Context, formats strfmt.Registry) error {

	if m.AmazonOrderReferenceID != nil {
		if err := m.AmazonOrderReferenceID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amazon_order_reference_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amazon_order_reference_id")
			}
			return err
		}
	}

	return nil
}

func (m *QuoteDataCartExtensionInterface) contextValidateShippingAssignments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ShippingAssignments); i++ {

		if m.ShippingAssignments[i] != nil {
			if err := m.ShippingAssignments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shipping_assignments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shipping_assignments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *QuoteDataCartExtensionInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuoteDataCartExtensionInterface) UnmarshalBinary(b []byte) error {
	var res QuoteDataCartExtensionInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
