// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuoteDataTotalsExtensionInterface ExtensionInterface class for @see \Magento\Quote\Api\Data\TotalsInterface
//
// swagger:model quote-data-totals-extension-interface
type QuoteDataTotalsExtensionInterface struct {

	// coupon label
	CouponLabel string `json:"coupon_label,omitempty"`
}

// Validate validates this quote data totals extension interface
func (m *QuoteDataTotalsExtensionInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quote data totals extension interface based on context it is used
func (m *QuoteDataTotalsExtensionInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuoteDataTotalsExtensionInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuoteDataTotalsExtensionInterface) UnmarshalBinary(b []byte) error {
	var res QuoteDataTotalsExtensionInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
