// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// QuoteDataTotalsItemExtensionInterface ExtensionInterface class for @see \Magento\Quote\Api\Data\TotalsItemInterface
//
// swagger:model quote-data-totals-item-extension-interface
type QuoteDataTotalsItemExtensionInterface interface{}
