// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuoteDataTotalSegmentExtensionInterface ExtensionInterface class for @see \Magento\Quote\Api\Data\TotalSegmentInterface
//
// swagger:model quote-data-total-segment-extension-interface
type QuoteDataTotalSegmentExtensionInterface struct {

	// tax grandtotal details
	TaxGrandtotalDetails []*TaxDataGrandTotalDetailsInterface `json:"tax_grandtotal_details"`

	// vertex tax calculation messages
	VertexTaxCalculationMessages []string `json:"vertex_tax_calculation_messages"`
}

// Validate validates this quote data total segment extension interface
func (m *QuoteDataTotalSegmentExtensionInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTaxGrandtotalDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuoteDataTotalSegmentExtensionInterface) validateTaxGrandtotalDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.TaxGrandtotalDetails) { // not required
		return nil
	}

	for i := 0; i < len(m.TaxGrandtotalDetails); i++ {
		if swag.IsZero(m.TaxGrandtotalDetails[i]) { // not required
			continue
		}

		if m.TaxGrandtotalDetails[i] != nil {
			if err := m.TaxGrandtotalDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tax_grandtotal_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tax_grandtotal_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this quote data total segment extension interface based on the context it is used
func (m *QuoteDataTotalSegmentExtensionInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTaxGrandtotalDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuoteDataTotalSegmentExtensionInterface) contextValidateTaxGrandtotalDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TaxGrandtotalDetails); i++ {

		if m.TaxGrandtotalDetails[i] != nil {
			if err := m.TaxGrandtotalDetails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tax_grandtotal_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tax_grandtotal_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *QuoteDataTotalSegmentExtensionInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuoteDataTotalSegmentExtensionInterface) UnmarshalBinary(b []byte) error {
	var res QuoteDataTotalSegmentExtensionInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
