// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VertexTaxDataCommodityCodeInterface Data model representing a Commmodity Code
//
// swagger:model vertex-tax-data-commodity-code-interface
type VertexTaxDataCommodityCodeInterface struct {

	// Commodity code
	Code string `json:"code,omitempty"`

	// Commodity code type
	Type string `json:"type,omitempty"`
}

// Validate validates this vertex tax data commodity code interface
func (m *VertexTaxDataCommodityCodeInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vertex tax data commodity code interface based on context it is used
func (m *VertexTaxDataCommodityCodeInterface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VertexTaxDataCommodityCodeInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VertexTaxDataCommodityCodeInterface) UnmarshalBinary(b []byte) error {
	var res VertexTaxDataCommodityCodeInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
